// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adguard} from '../models';

export function AdGuardConnect(arg1:string):Promise<void>;

export function AdGuardDisconnect():Promise<void>;

export function AdGuardExclusionsAdd(arg1:Array<string>):Promise<void>;

export function AdGuardExclusionsRemove(arg1:string):Promise<void>;

export function AdGuardExclusionsShow():Promise<Array<string>>;

export function AdGuardGetExclusionMode():Promise<adguard.ExclusionMode>;

export function AdGuardGetLocations():Promise<Array<adguard.Location>>;

export function AdGuardSetExclusionMode(arg1:adguard.ExclusionMode):Promise<void>;

export function AddFavoriteLocation(arg1:string):Promise<void>;

export function GetAdGuardAccount():Promise<adguard.Account>;

export function GetAdGuardBin():Promise<string>;

export function GetAdGuardStatus():Promise<adguard.Status>;

export function GetAdGuardVersion():Promise<string>;

export function GetFavoriteLocations():Promise<Array<string>>;

export function PickFilePath():Promise<string>;

export function RemoveFavoriteLocation(arg1:string):Promise<void>;

export function UpdateAdGuardBin(arg1:string):Promise<string>;
