// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adguard} from '../models';

export function GetAdGuardAccount():Promise<adguard.Account>;

export function GetAdGuardBin():Promise<string>;

export function GetAdGuardStatus():Promise<adguard.Status>;

export function GetAdGuardVersion():Promise<string>;

export function PickFilePath():Promise<string>;

export function UpdateAdGuardBin(arg1:string):Promise<string>;
