// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdGuardGetLocations() {
  return window['go']['main']['App']['AdGuardGetLocations']();
}

export function GetAdGuardAccount() {
  return window['go']['main']['App']['GetAdGuardAccount']();
}

export function GetAdGuardBin() {
  return window['go']['main']['App']['GetAdGuardBin']();
}

export function GetAdGuardStatus() {
  return window['go']['main']['App']['GetAdGuardStatus']();
}

export function GetAdGuardVersion() {
  return window['go']['main']['App']['GetAdGuardVersion']();
}

export function PickFilePath() {
  return window['go']['main']['App']['PickFilePath']();
}

export function UpdateAdGuardBin(arg1) {
  return window['go']['main']['App']['UpdateAdGuardBin'](arg1);
}
