// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdGuardConnect(arg1) {
  return window['go']['main']['App']['AdGuardConnect'](arg1);
}

export function AdGuardDisconnect() {
  return window['go']['main']['App']['AdGuardDisconnect']();
}

export function AdGuardExclusionsAdd(arg1) {
  return window['go']['main']['App']['AdGuardExclusionsAdd'](arg1);
}

export function AdGuardExclusionsRemove(arg1) {
  return window['go']['main']['App']['AdGuardExclusionsRemove'](arg1);
}

export function AdGuardExclusionsShow() {
  return window['go']['main']['App']['AdGuardExclusionsShow']();
}

export function AdGuardGetExclusionMode() {
  return window['go']['main']['App']['AdGuardGetExclusionMode']();
}

export function AdGuardGetLocations() {
  return window['go']['main']['App']['AdGuardGetLocations']();
}

export function AdGuardSetExclusionMode(arg1) {
  return window['go']['main']['App']['AdGuardSetExclusionMode'](arg1);
}

export function AddFavoriteLocation(arg1) {
  return window['go']['main']['App']['AddFavoriteLocation'](arg1);
}

export function GetAdGuardAccount() {
  return window['go']['main']['App']['GetAdGuardAccount']();
}

export function GetAdGuardBin() {
  return window['go']['main']['App']['GetAdGuardBin']();
}

export function GetAdGuardStatus() {
  return window['go']['main']['App']['GetAdGuardStatus']();
}

export function GetAdGuardVersion() {
  return window['go']['main']['App']['GetAdGuardVersion']();
}

export function GetFavoriteLocations() {
  return window['go']['main']['App']['GetFavoriteLocations']();
}

export function PickFilePath() {
  return window['go']['main']['App']['PickFilePath']();
}

export function RemoveFavoriteLocation(arg1) {
  return window['go']['main']['App']['RemoveFavoriteLocation'](arg1);
}

export function UpdateAdGuardBin(arg1) {
  return window['go']['main']['App']['UpdateAdGuardBin'](arg1);
}
